### ISSUE TITLE
Implementation with diffusion models

### ISSUE THREAD

**Issue by secuongle** [minha12/StyleAdv#2]
Hi,

Very interesting idea. I just wonder if you considered an implementation with diffusion models? Would be awesome to if this could work with Stable Diffusion pipeline, for example.

**Comment by annaandersson95** [comment]
Hi, 

The attacks need a generative model which has a disentangled latent space. The Stable Diffusion does not has this feature compared to StyleGAN. Anyway, we at least tried implementing the attack with DiffAE, however, the manifold of this model is too sensitive to changes so the attacks usually created face-swapping effect, which is not our goal.

**Comment by minha12** [comment]
> Hi,
> 
> If I understand correctly, the attacks need a generative model which has a disentangled latent space. The Stable Diffusion does not has this feature compared to StyleGAN. Anyway, I tried implementing the attack with DiffAE, however, the manifold of this model is too sensitive to changes so the attacks usually created face-swapping effect, which is not the goal.

Correct! We tried DiffAE too and got similar results as you mentioned.

**Comment by minha12** [comment]
> Hi,
> 
> Very interesting idea. I just wonder if you considered an implementation with diffusion models? Would be awesome to if this could work with Stable Diffusion pipeline, for example.

The follow-up work is in progress, please wait for it :D
